/* global React */
// ============================================================================
// OBRAS · DATA — 21 obras com fotos e dados reais
// ============================================================================

const WP = 'https://www.bertiestrutural.com.br/wp-content/uploads';

const OBRAS_CATS = [
  { key: 'todas',        label: 'Todas' },
  { key: 'supermercado', label: 'Supermercado' },
  { key: 'industrial',   label: 'Industrial' },
  { key: 'comercial',    label: 'Comercial' },
];

const OBRAS_LIST = [
  { id: 1,  cat: 'supermercado', cover: 'assets/photos/supermercado-hmais-capa.jpg',     title: 'Supermercado Hmais',      catLabel: 'Supermercado', city: 'Palmeira – PR',           area: '3.105 m²',  status: 'Entregue', desc: 'O Supermercado Hmais contou com a atuação da Berti Estrutural no desenvolvimento e execução da estrutura metálica, com tesouras treliçadas apoiadas em pilares de concreto, proporcionando grandes vãos livres.', gallery: ['assets/photos/supermercado-hmais-capa.jpg','assets/photos/supermercado-hmais-01.jpg','assets/photos/supermercado-hmais-02.jpg','assets/photos/supermercado-hmais-03.jpg','assets/photos/supermercado-hmais-04.jpg','assets/photos/supermercado-hmais-05.jpg','assets/photos/supermercado-hmais-06.jpg','assets/photos/supermercado-hmais-07.jpg'] },
  { id: 2,  cat: 'supermercado', cover: 'assets/photos/supermercado-camilo-capa.jpg',    title: 'Supermercado Camilo',     catLabel: 'Supermercado', city: 'Marialva – PR',           area: '9.000 m²',  status: 'Entregue', desc: 'O novo Supermercado Camilo reforça a parceria entre a Rede Camilo e a Berti Estrutural, com solução completa de fechamento metálico, cobertura zipada e sistema termoacústico. Desenvolvido 100% em BIM.', gallery: ['assets/photos/supermercado-camilo-capa.jpg','assets/photos/supermercado-camilo-01.jpg','assets/photos/supermercado-camilo-02.jpg','assets/photos/supermercado-camilo-03.jpg','assets/photos/supermercado-camilo-04.jpg','assets/photos/supermercado-camilo-05.jpg','assets/photos/supermercado-camilo-06.jpg'] },
  { id: 3,  cat: 'industrial',   cover: 'assets/photos/transportadora-falcao-capa.jpg', title: 'Transportadora Falcão',   catLabel: 'Industrial',   city: 'Uruguaiana – RS',         area: '6.100 m²',  status: 'Entregue', desc: 'Ampliação da Transportadora Falcão com estrutura metálica mista.', gallery: ['assets/photos/transportadora-falcao-capa.jpg','assets/photos/transportadora-falcao-01.jpg','assets/photos/transportadora-falcao-02.jpg','assets/photos/transportadora-falcao-03.jpg','assets/photos/transportadora-falcao-04.jpg','assets/photos/transportadora-falcao-05.jpg'] },
  { id: 4,  cat: 'industrial',   cover: 'assets/photos/comercial-ivaipora-capa.jpg',    title: 'Comercial Ivaiporã',      catLabel: 'Industrial',   city: 'Ivaiporã – PR',           area: '17.000 m²', status: 'Entregue', desc: 'Galpão logístico com estrutura metálica mista em Ivaiporã.', gallery: ['assets/photos/comercial-ivaipora-capa.jpg','assets/photos/comercial-ivaipora-01.jpg','assets/photos/comercial-ivaipora-02.jpg','assets/photos/comercial-ivaipora-03.jpg','assets/photos/comercial-ivaipora-04.jpg','assets/photos/comercial-ivaipora-05.jpg','assets/photos/comercial-ivaipora-06.jpg'] },
  { id: 5,  cat: 'industrial',   cover: 'assets/photos/viacao-garcia-capa.jpg',          title: 'Viação Garcia',           catLabel: 'Industrial',   city: 'Londrina – PR',           area: '18.000 m²', status: 'Entregue', desc: 'Galpão logístico, execução de cobertura em estrutura metálica 100% em aço de alta resistência, apoiadas sobre pilares e vigas de concreto armado, ligações parafusadas e telhas térmicas. Tempo de execução 150 dias.', gallery: ['assets/photos/viacao-garcia-capa.jpg','assets/photos/viacao-garcia-01.jpg','assets/photos/viacao-garcia-02.jpg','assets/photos/viacao-garcia-03.jpg','assets/photos/viacao-garcia-04.jpg','assets/photos/viacao-garcia-05.jpg'] },
  { id: 6,  cat: 'supermercado', cover: 'assets/photos/muffato-apucarana-capa.jpg',     title: 'Muffato Apucarana',       catLabel: 'Supermercado', city: 'Apucarana – PR',          area: '7.300 m²',  status: 'Entregue', desc: 'Supermercado Muffato com estrutura metálica mista.', gallery: ['assets/photos/muffato-apucarana-capa.jpg','assets/photos/muffato-apucarana-01.jpg','assets/photos/muffato-apucarana-02.jpg','assets/photos/muffato-apucarana-03.jpg','assets/photos/muffato-apucarana-05.jpg'] },
  { id: 7,  cat: 'comercial',    cover: 'assets/photos/fast-gondolas-capa.jpg',          title: 'Fast Gôndolas',           catLabel: 'Comercial',    city: 'Londrina – PR',           area: '13.000 m²', status: 'Entregue', desc: 'Galpão logístico com estrutura metálica mista.', gallery: ['assets/photos/fast-gondolas-capa.jpg','assets/photos/fast-gondolas-01.jpg','assets/photos/fast-gondolas-02.jpg','assets/photos/fast-gondolas-03.jpg','assets/photos/fast-gondolas-04.jpg'] },
  { id: 8,  cat: 'comercial',    cover: 'assets/photos/balaroti-capa.jpg',               title: 'Balaroti',                catLabel: 'Comercial',    city: 'Londrina – PR',           area: '2.000 m²',  status: 'Entregue', desc: 'Materiais de construção — estrutura metálica mista.', gallery: ['assets/photos/balaroti-capa.jpg','assets/photos/balaroti-01.jpg','assets/photos/balaroti-02.jpg','assets/photos/balaroti-03.jpg','assets/photos/balaroti-04.jpg','assets/photos/balaroti-05.jpg'] },
  { id: 9,  cat: 'comercial',    cover: 'assets/photos/carbamall-capa.jpg',              title: 'Carbamall',               catLabel: 'Comercial',    city: 'Londrina – PR',           area: '2.700 m²',  status: 'Entregue', desc: 'Open Mall executado 100% em estruturas metálicas, com concepção limpa e otimizada.', gallery: ['assets/photos/carbamall-capa.jpg','assets/photos/carbamall-01.jpg','assets/photos/carbamall-02.jpg','assets/photos/carbamall-05.jpg','assets/photos/carbamall-07.jpg'] },
  { id: 10, cat: 'supermercado', cover: 'assets/photos/muffato-beltrao-capa.jpg',       title: 'Muffato Beltrão',         catLabel: 'Supermercado', city: 'Francisco Beltrão – PR',  area: '8.600 m²',  status: 'Entregue', desc: 'Projeto das estruturas metálicas de cobertura e montagem de painéis de fechamento, telhas zipadas, isolamento com lã de vidro. Tempo de execução 120 dias.', youtube: 'https://youtu.be/noonzrTGMuY', gallery: ['assets/photos/muffato-beltrao-capa.jpg','assets/photos/muffato-beltrao-01.jpg','assets/photos/muffato-beltrao-02.jpg','assets/photos/muffato-beltrao-03.jpg','assets/photos/muffato-beltrao-04.jpg'] },
  { id: 11, cat: 'supermercado', cover: 'assets/photos/bavaresco-capa.jpg',             title: 'Bavaresco',               catLabel: 'Supermercado', city: 'Pontal do Paraná – PR',   area: '9.000 m²',  status: 'Entregue', desc: 'Supermercado com aço galvanizado e pintura eletrostática, garantindo proteção duplex ideal para ambientes marinhos.', youtube: 'https://youtu.be/hOtbZm8Cig8', gallery: ['assets/photos/bavaresco-capa.jpg','assets/photos/bavaresco-01.jpg','assets/photos/bavaresco-02.jpg','assets/photos/bavaresco-03.jpg'] },
  { id: 12, cat: 'supermercado', cover: 'assets/photos/super-88-capa.jpg',              title: 'Super 88',                catLabel: 'Supermercado', city: 'Londrina – PR',           area: '6.500 m²',  status: 'Entregue', desc: 'Estrutura 100% parafusada em aço galvanizado de alta resistência. Tempo de execução 140 dias.', gallery: ['assets/photos/super-88-capa.jpg','assets/photos/super-88-01.jpg','assets/photos/super-88-02.jpg','assets/photos/super-88-03.jpg','assets/photos/super-88-04.jpg'] },
  { id: 13, cat: 'industrial',   cover: 'assets/photos/tic-curitiba-capa.jpg',          title: 'TIC Curitiba',            catLabel: 'Industrial',   city: 'Curitiba – PR',           area: '6.780 m²',  status: 'Entregue', desc: 'Galpão logístico com cobertura em estrutura metálica 100% em aço de alta resistência, ligações parafusadas e telhas térmicas. Tempo de execução 120 dias.', youtube: 'https://youtu.be/pbokdWQA8Rk', gallery: ['assets/photos/tic-curitiba-capa.jpg','assets/photos/tic-curitiba-01.jpg','assets/photos/tic-curitiba-02.jpg','assets/photos/tic-curitiba-03.jpg','assets/photos/tic-curitiba-04.jpg','assets/photos/tic-curitiba-056.jpg','assets/photos/tic-curitiba-06.jpg'] },
  { id: 14, cat: 'supermercado', cover: 'assets/photos/super-golff-01.jpg',             title: 'Super Golff',             catLabel: 'Supermercado', city: 'Cambé – PR',              area: '4.600 m²',  status: 'Entregue', desc: 'Cobertura em estrutura metálica 100% em aço de alta resistência, apoiadas sobre pilares e vigas de concreto armado, telhas termo-acústicas. Tempo de execução 120 dias.', youtube: 'https://youtu.be/xZDdovfEZ7w', gallery: ['assets/photos/super-golff-01.jpg','assets/photos/super-golff-02.jpg','assets/photos/super-golff-03.jpg','assets/photos/super-golff-04.jpg','assets/photos/super-golff-05.jpg'] },
  { id: 15, cat: 'supermercado', cover: 'assets/photos/muffato-medianeira-capa.jpg',   title: 'Muffato Medianeira',      catLabel: 'Supermercado', city: 'Medianeira – PR',         area: '11.100 m²', status: 'Entregue', desc: 'Estruturas metálicas de cobertura, painéis de fechamento, telhas zipadas com isolamento lã de vidro, calhas e rufos. Tempo de execução 120 dias.', youtube: 'https://youtu.be/4qlqqPA_6hs', gallery: ['assets/photos/muffato-medianeira-capa.jpg','assets/photos/muffato-medianeira-01.jpg','assets/photos/muffato-medianeira-02.jpg','assets/photos/muffato-medianeira-03.jpg','assets/photos/muffato-medianeira-04.jpg'] },
  { id: 16, cat: 'comercial',    cover: 'assets/photos/chacara-graciosa-capa.jpg',      title: 'Chácara Graciosa',        catLabel: 'Comercial',    city: 'Londrina – PR',           area: '1.000 m²',  status: 'Entregue', desc: 'Edifício para eventos com estrutura 100% metálica, cobertura termoacústica, fechamento com painéis metálicos. Tempo de execução 90 dias.', gallery: ['assets/photos/chacara-graciosa-capa.jpg','assets/photos/chacara-graciosa-01.jpg','assets/photos/chacara-graciosa-02.jpg','assets/photos/chacara-graciosa-03.jpg','assets/photos/chacara-graciosa-04.jpg','assets/photos/chacara-graciosa-05.jpg','assets/photos/chacara-graciosa-06.jpg'] },
  { id: 17, cat: 'comercial',    cover: 'assets/photos/jeep-maringa-capa.jpg',          title: 'Jeep Maringá',            catLabel: 'Comercial',    city: 'Maringá – PR',            area: '1.800 m²',  status: 'Entregue', desc: 'Edificação comercial com pórticos de alma cheia e estrutura secundária em Light Steel Frame. Obra turn key. Tempo de execução 120 dias.', gallery: ['assets/photos/jeep-maringa-capa.jpg','assets/photos/jeep-maringa-01.jpg','assets/photos/jeep-maringa-02.jpg','assets/photos/jeep-maringa-03.jpg'] },
  { id: 18, cat: 'comercial',    cover: 'assets/photos/millenium-mall-capa.jpg',        title: 'Millenium Mall',          catLabel: 'Comercial',    city: 'Londrina – PR',           area: '1.750 m²',  status: 'Entregue', desc: 'Open Mall com estruturas metálicas em aço galvanizado, soluções para pele de vidro e pergolados. Tempo de execução 90 dias.', youtube: 'https://youtu.be/Pj-tA7g7X1w', gallery: ['assets/photos/millenium-mall-capa.jpg','assets/photos/millenium-mall-01.jpg','assets/photos/millenium-mall-02.jpg','assets/photos/millenium-mall-03.jpg','assets/photos/millenium-mall-04.jpg','assets/photos/millenium-mall-05.jpg','assets/photos/millenium-mall-06.jpg'] },
  { id: 19, cat: 'comercial',    cover: 'assets/photos/inga-mall-capa.jpg',             title: 'Inga Mall',               catLabel: 'Comercial',    city: 'Londrina – PR',           area: '3.095 m²',  status: 'Entregue', desc: 'Edificação com estruturas metálicas em aço galvanizado. Soluções diferenciadas para marquises e pergolados. Prazo de execução: 100 dias.', youtube: 'https://youtu.be/4ufbxSeGn6E', gallery: ['assets/photos/inga-mall-capa.jpg','assets/photos/inga-mall-01.jpg','assets/photos/inga-mall-02.jpg','assets/photos/inga-mall-03.jpg','assets/photos/inga-mall-04.jpg','assets/photos/inga-mall-05.jpg'] },
  { id: 20, cat: 'comercial',    cover: 'assets/photos/tropical-mall-capa.jpg',         title: 'Tropical Mall',           catLabel: 'Comercial',    city: 'Cambé – PR',              area: '2.700 m²',  status: 'Entregue', desc: 'Open mall 100% em estruturas metálicas. Soluções diferenciadas para fixação de pele de vidro e pergolados. Prazo de execução: 90 dias.', gallery: ['assets/photos/tropical-mall-capa.jpg','assets/photos/tropical-mall-01.jpg','assets/photos/tropical-mall-02.jpg','assets/photos/tropical-mall-03.jpg','assets/photos/tropical-mall-04.jpg','assets/photos/tropical-mall-05.jpg','assets/photos/tropical-mall-06.jpg','assets/photos/tropical-mall-07.jpg'] },
  { id: 21, cat: 'industrial',   cover: 'assets/photos/nippon-capa.jpg',               title: 'Nipponflex Espumação',    catLabel: 'Industrial',   city: 'Maringá – PR',            area: '15.000 m²', status: 'Entregue', desc: 'Cobertura e pilares para fechamento em estrutura metálica, aço galvanizado, ligações parafusadas, telhas termo-acústicas e ventiladores naturais.', youtube: 'https://youtu.be/02_BGZIFano', gallery: ['assets/photos/nippon-capa.jpg','assets/photos/nippon-01.jpg','assets/photos/nippon-02.jpg','assets/photos/nippon-03.jpg','assets/photos/nippon-04.jpg','assets/photos/nippon-05.jpg','assets/photos/nippon-06.jpg'] },
];

Object.assign(window, { OBRAS_CATS, OBRAS_LIST });
